version: '3.7'

services:
  ###########################################################################
  #######                  DB SERVICES                                #######
  ###########################################################################
  postgres:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./volumes/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=tagore,kavach
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"kavach\""
      timeout: 2s      
    networks:
      - tagore

  ###########################################################################
  #######                  APP SERVICES                               #######
  ###########################################################################
  tagore-server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./server/modelData:/app/modelData
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tagore
networks:
  tagore: