FROM node:18-alpine as build
WORKDIR /app

RUN apk update && apk add git

# install node modules
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm i --silent --legacy-peer-deps

# copy source files to image and build
COPY . .
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]